### ISSUE TITLE
Check SRU query

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#1012]
die UdK möchte nach längerer Pause mit ihrem Importprojekt RISM-Daten in den B3Kat einspielen weitermachen. Dafür habe ich die Abfrage "https://beta.rism.info/sru/sources?operation=searchRetrieve&version=1.1&query=rism.librarySiglum=D-Bhm%20AND%20rism.shelfmark=RH*&maximumRecords=10", die Sie mir dankenswerterweise beim letzten Mal zur Verfügung gestellt hatten, genutzt. Lediglich aus der 10 habe ich eine 100 gemacht.

Damit erhalte ich aber leider entweder 0 Treffer oder die Meldung java.lang.NullPointerException at SRUDownloader.start(SRUDowloader.java:35) at SRUDownloader.main(SRUDownloader.java:23).

 

Wähle ich anstelle von „rism.librarySiglum“ aber „bath.possessingInstitution“ aus, erhalte ich 4395 Treffer. Leider ist hier wieder unschöner Beifang dabei, da mir auch Treffer von anderen Institutionen ausgegeben werden, die ich nicht haben möchte, z.B. D-RUl (Kleines L, kein großes i), D-Rtt und D-MAS (jeweils 1-188 Treffer). Das gleiche Problem hatte ich vor 2 Jahren auch. Daher hatten Sie mir oben erwähnte Abfrage gegeben. (siehe unten angefügten Email-Verlauf)

 

Wo habe ich jetzt einen Fehler gemacht, dass es da plötzlich kein Ergebnis mehr gibt?

**Comment by HirschSt** [comment]
done with https://github.com/rism-digital/muscat/commit/fcb60cd71b0697a73003d0addd0ce80759345acf
